### ISSUE TITLE
'in' appears to work incorrectly for git

### ISSUE THREAD

**Issue by nkabir** [reinout/checkoutmanager#19]
Wonderful utility! Thanks so much for the great work :-)

The code below should return 0 but returns 1, incorrectly indicating that there are remote changes available:

```
>>> from checkoutmanager.utils import system
>>> output = system('git pull --dry-run').strip()
>>> output
''
>>> output = output.split('\n')
>>> output
['']
>>> len(output)
1
```

Relevant checkoutmanager code is here:

https://github.com/reinout/checkoutmanager/blob/master/checkoutmanager/dirinfo.py#L376

**Comment by reinout** [comment]
Thanks for the report! I've tried fixing it in #20.

Can you check if the latest release (2.5) works for you?
